config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/home', to: 'static_pages#home'
    resources :users, only: [ :index, :update ]

    resources :categories do
      resources :words
    end
  end

  #for showing results
  get 'words', to: 'words#show'

  #static pages
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  #user pages
  get 'signup', to: 'users#new'
  resources :users

  #lesson and answer pages
  resources :lessons, only: [ :new, :create, :show, :index ] do
    resources :answers, only: [ :new, :index, :show, :create ]
  end
  get '/categories', to: 'lessons#index'
  
  #session pages
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  #For the follow and unfollow function
  resources :relationships, only: [:create, :destroy]

end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category

  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  has_one :correct_choice, -> { where isCorrect: true }, class_name: "Choice"

  has_one :answer, dependent: :destroy

  #validations
  validates :content, presence: true, length: { minimum: 3 }
  validate :has_one_correct_choice
  validate :unique_choices

  def has_one_correct_choice
    len = choices.select{|choice| choice.isCorrect }.length
    if len > 1
      return errors.add :base, "A Word can contain ONLY ONE correct answer!"
    elsif len==0
      return errors.add :base, "A Word SHOULD HAVE ONE correct answer!"
    end
  end

  def unique_choices
    if choices.uniq {|c| [c.content.downcase]}.length < choices.length
      return errors.add :base, "Choices should be unique."
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_only

  def index
    @category = Category.find(params[:category_id])
    @words = @category.words.paginate(page: params[:page], per_page: 10).order('updated_at DESC')
  end

  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.build
    3.times { @word.choices.build }
  end

  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.build(word_params)

    if @word.save
      flash[:success] = "You have successfully added a new word"
      redirect_to admin_category_words_url(@category)
    else 
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])

    if @word.update_attributes(word_params)
      flash[:success] = "You have successfully updated the word!"
      redirect_to admin_category_words_url(@category)
    else 
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])

    if @word.destroy
      flash[:warning] = "You have successfully deleted the word."
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def word_params
      params.require(:word).permit(:id, :content, { choices_attributes: [ :id, :content, :isCorrect ] })
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :logged_in_user
  
  def show
    lessons = Lesson.where(user_id: current_user.id)
    @words = find_words(lessons).paginate(page: params[:page], per_page: 10)
  end

  
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
  def find_words(lessons)
    words = []

    lessons.each do |lesson|
      lesson.words.each do |word|
        answer = user_answer(lesson, word)
        correct_choice = Choice.where(word_id: word.id, isCorrect: 1)
        words.push(word: word, answer: answer, correct_choice: correct_choice)
      end
    end

    return words
  end
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @category, @word ] do |f| %>
    <%= render 'shared/error_messages',object: f.object %>
    <div class="form-group">
        <%= f.label :content, "Word" %>
        <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :choices, "Choices" %>
        <%= f.fields_for :choices do |choices| %>
            <%= choices.text_field :content, class: "form-control" %>
            <%= choices.check_box :isCorrect %>
            <%= choices.label :isCorrect, "Check if this is the correct answer." %>
        <% end %>
    </div>
    <div class="form-group">
        <%= f.submit msg, class: "btn btn-block btn-primary" %>
    </div>
<% end %>

app/views/admin/words/edit.html.erb
<% provide(:title, "Edit Word") %>

<div class="jumbotron mt-2">
    <h3 class='text-center usersheader'>Edit this Word</h3>
    <div class="row new mt-4 d-flex justify-content-center">
        <div class="form">
            <div class="container mt-4">
                <%= render 'form', msg: "Update Word" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <%= link_to "Back to Word List", admin_category_words_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>

app/views/admin/words/index.html.erb
<% provide(:title, "Categories") %>

<div class="jumbotron mt-2">
    <h3 class='text-center usersheader'>Administrate Words</h3>
    <div class='mt-2'>
        <div class="row">
            <div class="col-lg-4 col-sm-12"></div>
            <div class="col-lg-4 col-sm-12">
                <div class="d-flex justify-content-center">
                    <%= will_paginate @words %>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 d-flex justify-content-center">
                <%= link_to "Create New Word", new_admin_category_word_path, class: "btn btn-primary create-btn" %>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <table class="table">
                <thead class="thead-white">
                    <tr>
                        <th scope="col">Word</th>
                        <th scope="col">Answer</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="tbody-white">
                    <% @words.each do |word| %>
                        <tr>
                            <th class="vertical-align-center" scope="row">
                                <%= word.content %>
                            </th>
                            <td>
                                <%= word.correct_choice.content %>
                            </td>
                            <td class="vertical-align-center d-flex justify-content-center">
                                <%= link_to edit_admin_category_word_path(@category, word), class: "btn btn-primary action" do %>
                                    <i class='fa fa-pencil-square-o'></i>
                                <% end %>
                                <%= button_to admin_category_word_path(@category, word), method: :delete , class: "btn btn-danger action", 
                                    data: {confirm: "Are you sure you want to delete this word?"} do %>
                                        <i class="fa fa-trash-o"></i>
                                 <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <%= will_paginate @words %>
    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <%= link_to "Back to Category List", admin_categories_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>

app/views/admin/words/new.html.erb
<% provide(:title, "New Word") %>

<div class="jumbotron mt-2">
    <h3 class='text-center usersheader'>Create a New Word</h3>
    <div class="row new mt-4 d-flex justify-content-center">
        <div class="form">
            <div class="container mt-4">
                <%= render 'form', msg: "Create Word" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <%= link_to "Back to Word List", admin_category_words_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>