config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/home', to: 'static_pages#home'
    resources :users, only: [ :index, :update ]

    resources :categories do
      resources :words
    end
  end

  #for showing results
  get 'words', to: 'words#show'

  #static pages
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  #user pages
  get 'signup', to: 'users#new'
  resources :users

  #lesson and answer pages
  resources :lessons, only: [ :new, :create, :show, :index ] do
    resources :answers, only: [ :new, :index, :show, :create ]
  end
  get '/categories', to: 'lessons#index'
  
  #session pages
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  #For the follow and unfollow function
  resources :relationships, only: [:create, :destroy]

end

app/views/shared/_activity.html.erb
<div class="card mt-2 activity-card">
    <div class="card-body text-align-center">
        <h3 class="card-title">
            Activity Feed
        </h3>
    </div>
    <div class="d-flex justify-content-center">
        <%= will_paginate @activities %>
    </div>
</div>

<ul class="list-group mt-2 activity-card">
    <% if @activities.empty? %>
        <li class="list-group-item">
            <p class="text-black-50 font-italic vertical-align-center">
                This user is rather lazy, and does not have any activities yet.
            </p>
        </li>
    <% else %>
        <% @activities.each do |activity| %>
            <li class="list-group-item">
                <% person = User.find(activity.user_id) %>
                <%= user_avatar(person, "dp") %>
                <% if activity.action_type == "Lesson" %>
                    <% lesson = Lesson.find_by_id(activity.action_id) %>
                    <strong><%= link_to person.name, user_path(person), class: "text-primary"%></strong>
                    &nbsp;learned <%= lesson.result %> out of <%= lesson.category.words.count %> in 
                    <strong><%= link_to lesson.category.title, lesson_path(lesson.id), class: "text-primary" %></strong>
                <% else %>
                    <% followed = find_relationship(activity.action_id) %>
                    <strong><%= link_to person.name, user_path(person), class: "text-primary" %></strong>
                    &nbsp;followed&nbsp;
                    <strong><%= link_to followed.name, user_path(followed), class: "text-primary" %></strong>
                <% end %>
                <p class="float-right text-black-50 font-italic">
                    <%= time_ago_in_words(activity.created_at) %> ago
                </p>
            </li>
        <% end %>
    <% end %>
</ul>

<div class="mt-3 d-flex justify-content-center">
    <%= will_paginate @activities %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        <strong>This form contains errors.</strong>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_profile.html.erb
<% provide(:title, @user.name) %>

<div class="card mt-2 profile-card">
    <div class="card-body text-align-center">
        <%= user_avatar(@user, "profile-pic") %>
        <h5 class="card-title mt-3">
            <%= @user.name %>
        </h5>
        <%= link_to 'Admin Page', admin_home_path, class: "btn btn-info" if logged_in? && current_user.isAdmin && current_user == @user%>
        <p class="card-text mt-2"><%= @user.email %></p>
        <%= render 'users/follow_form' if logged_in? %>
    </div>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="card-text d-flex justify-content-center">
                <strong id="followers"><%= @user.followers.count %></strong>&nbsp;Followers&nbsp;|&nbsp; 
                <strong><%= @user.followed_users.count %></strong>&nbsp;Following
            </div>
        </li>
    </ul>

    <% if @user.id == current_user.id %>
        <div class="row mt-2">
            <div class="col-12 d-flex justify-content-center">
                <strong><%= link_to words_learned(current_user), words_path %></strong><br>
            </div>
            <div class="col-12 d-flex justify-content-center">
                <p>Words Learned</p>
            </div>
        </div> 
    <% end %>
</div>