config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/home', to: 'static_pages#home'
    resources :users, only: [ :index, :update ]

    resources :categories do
      resources :words
    end
  end

  #for showing results
  get 'words', to: 'words#show'

  #static pages
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  #user pages
  get 'signup', to: 'users#new'
  resources :users

  #lesson and answer pages
  resources :lessons, only: [ :new, :create, :show, :index ] do
    resources :answers, only: [ :new, :index, :show, :create ]
  end
  get '/categories', to: 'lessons#index'
  
  #session pages
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  #For the follow and unfollow function
  resources :relationships, only: [:create, :destroy]

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :activity, optional: true

  has_many :answers, dependent: :destroy
  has_many :words, through: :category

  has_one :activity, as: :action, dependent: :destroy
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_action :logged_in_user
  before_action only: [ :show ] do 
    lesson_exists(params[:id])
  end
  before_action :unstarted_lesson, only: [ :new ]
  before_action :finished_lesson, only: [ :show ]
  before_action :correct_user, only: [ :show ]

  def index
    @lesson = Lesson.new
    status = params[:status] if params[:status].present?
    
  
    if status.present?
      @categories = finished_lessons(current_user).paginate(page: params[:page], per_page: 12) if status=="1"
      @categories = unfinished_lessons(current_user).paginate(page: params[:page], per_page: 12) if status=="0"
    else  
      @categories = Category.paginate(page: params[:page], per_page: 12)
    end
  end

  def new
  end

  def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
      user = User.find(@lesson.user_id)
      @lesson.create_activity(user: user)
      redirect_to new_lesson_answer_url(@lesson)
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
    @words = @lesson.category.words.paginate(page: params[:page], per_page: 10)
  end

  private
    def lesson_params
      params.require(:lesson).permit(:user_id, :category_id, :result)
    end

    def correct_user
      lesson = Lesson.find(params[:id])
      if lesson.user_id != current_user.id
        flash[:danger] = "You are unauthorized to view the page. The result of that lesson does not belong to you."
        redirect_to categories_url
      end
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def calculate_results(lesson)
    result = 0

    lesson.answers.each do |answer|
      word = Word.find(answer.word_id)
      if answer.choice_id == word.correct_choice.id 
        result+=1
      end
    end
    lesson.update_attributes(result: result)
  end

  def lesson_finished?(lesson)
    lesson.category.words.count == lesson.answers.count
  end

  def unstarted_lesson 
    if params[:lesson_id].present?
      @lesson = Lesson.find(params[:lesson_id])
      if lesson_finished?(@lesson) 
        flash[:success] = "Good job for finishing this lesson!"
        redirect_to lesson_url(@lesson)
      end
    end
  end

  def answered_category?(user, category)
    return Lesson.find_by(category_id: category.id, user_id: user.id)
  end

  def finished_lesson
    lesson = Lesson.find(params[:id])
    if !lesson_finished?(lesson)
      flash[:danger] = "This result can still change. You can still continue answering this lesson. "
    end
  end

  def lesson_exists(id)
    if Lesson.find_by(id: id).nil?
      flash[:danger] = "This lesson has not been initiated. You may start taking a lesson by choosing from the categories below."
      redirect_to categories_url
    end
  end

  def user_answer(lesson, word)
    answer = lesson.answers.select{ |answer| answer.word_id == word.id }
    return Choice.find(answer[0][:choice_id])
  end
end

def finished_lessons(user)
  l = []

  categories = Category.all
  categories.each do |category|
    lesson = Lesson.find_by(category_id: category.id, user_id: user.id)

    if lesson.present? && lesson.answers.count == lesson.words.count 
      l.push(category)
    end
  end
  return l
end

def unfinished_lessons(user)
  l = []

  categories = Category.all
  categories.each do |category|
    lesson = Lesson.find_by(category_id: category.id, user_id: user.id)

    if lesson.present? && lesson.answers.count != lesson.words.count || lesson.nil?
      l.push(category)
    end
  end
  return l
end

app/views/lessons/index.html.erb
<% provide(:title, "Categories") %>

<div class="jumbotron mt-2">
    <h3 class='text-center usersheader'>Categories</h3>
    <div class='d-flex justify-content-center mt-3'>
        <%= link_to "All", categories_path, class: "btn btn-primary m-2 filter-btn" %>
        <%= link_to "Learned", categories_path(:status => 1), class: "btn btn-primary m-2 filter-btn" %>
        <%= link_to "Not Yet Learned", categories_path(:status => 0), class: "btn btn-primary m-2 filter-btn" %>
    </div>
    <div class='d-flex justify-content-center'>
        <%= will_paginate @categories %>
    </div>

    <ul class="userlist">
        <div class="row">
            <% @categories.each do |category| %>
                <div class="col-lg-4 col-sm-12 d-flex justify-content-center">
                    <li class="user">
                        <div class="row">
                            <div class="col-8 user-name d-flex justify-content-left">
                                <h5><%= category.title %></h5>
                            </div>
                            <div class="col-4">
                                <div class="float-right">
                                    <%= category.words.count %>&nbsp;Words
                                </div>
                            </div>
                        </div>
                        <div class="divider"></div>
                        <div class="row">
                            <div class="col-12">
                                <p><%= category.description %></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 vertical-align-center start-btn">
                                <% if answered_category?(current_user, category) %>
                                    <% lesson = answered_category?(current_user, category) %>
                                    <% if lesson_finished?(lesson) %>
                                        <%= link_to "Show results", lesson_path(lesson), class: "btn btn-warning" %>
                                    <% else %>
                                        <%= link_to "Continue", new_lesson_answer_path(lesson), class: "btn btn-secondary" %>
                                    <% end %>
                                <% else %>
                                    <%= form_for(@lesson) do |f| %>
                                        <%= f.hidden_field :category_id, value: category.id %>
                                        <%= f.hidden_field :user_id, value: current_user.id %>
                                        <%= f.submit "Start Lesson", class: "btn btn-info" %>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    </li>
                </div>
            <% end %>
        </div>
    </ul>
    <div class='d-flex justify-content-center'>
        <%= will_paginate @categories %>
    </div>
</div>

app/views/lessons/show.html.erb
<% provide(:title, "Result") %>

Result: <%= @lesson.result %> out of <%= @lesson.category.words.count %>