config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/home', to: 'static_pages#home'
    resources :users, only: [ :index, :update ]

    resources :categories do
      resources :words
    end
  end

  #for showing results
  get 'words', to: 'words#show'

  #static pages
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  #user pages
  get 'signup', to: 'users#new'
  resources :users

  #lesson and answer pages
  resources :lessons, only: [ :new, :create, :show, :index ] do
    resources :answers, only: [ :new, :index, :show, :create ]
  end
  get '/categories', to: 'lessons#index'
  
  #session pages
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  #For the follow and unfollow function
  resources :relationships, only: [:create, :destroy]

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 5 }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  before_action :logged_in_user
  before_action :admin_only

  def index
    @categories = Category.paginate(page: params[:page], per_page: 9).order('updated_at DESC')
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "You have successfully added a new category!"
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:success] = "You have successfully updated the category!"
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:warning] = "You have successfully deleted the category!"
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "You cannot delete the category!"
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category ] do |f| %>
    <%= render 'shared/error_messages',object: f.object %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.submit msg, class: "btn btn-block btn-primary" %>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide(:title, "Edit Category") %>

<div class="jumbotron mt-2">
    <h3 class='text-center usersheader'>Edit this Category</h3>
    <div class="row new mt-4 d-flex justify-content-center">
        <div class="form">
            <div class="container mt-4">
                <%= render 'form', msg: "Update Category" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <%= link_to "Back to Category List", admin_categories_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, "Categories") %>

<div class="jumbotron mt-2">
    <h3 class='text-center usersheader'>List of Categories</h3>
    <div class='mt-2'>
        <div class="row">
            <div class="col-lg-4 col-sm-12"></div>
            <div class="col-lg-4 col-sm-12">
                <div class="d-flex justify-content-center">
                    <%= will_paginate @categories %>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 d-flex justify-content-center">
                <%= link_to "Create New Category", new_admin_category_path, class: "btn btn-primary create-btn" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead class="thead-white">
                    <tr>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="tbody-white">
                    <% @categories.each do |category| %>
                        <tr>
                            <th class="vertical-align-center" scope="row">
                                <%= link_to category.title, admin_category_words_path(category) %>
                            </th>
                            <td><%= category.description %></td>
                            <td class="d-flex justify-content-center">
                                <%= button_to edit_admin_category_path(category), method: :get , class: "btn btn-primary action" do %>
                                    <i class='fa fa-pencil-square-o'></i>
                                <% end %>
                                <%= button_to admin_category_path(category), method: :delete , class: "btn btn-danger action", 
                                    data: {confirm: "Are you sure you want to delete this category?"} do %>
                                        <i class="fa fa-trash-o"></i>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <%= will_paginate @categories %>
    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <%= link_to "Back to Admin Dashboard", admin_home_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>

app/views/admin/categories/new.html.erb
<% provide(:title, "New Category") %>

<div class="jumbotron mt-2">
    <h3 class='text-center usersheader'>Create a New Category</h3>
    <div class="row new mt-4 d-flex justify-content-center">
        <div class="form">
            <div class="container mt-4">
                <%= render 'form', msg: "Create Category" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <%= link_to "Back to Category List", admin_categories_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>